# Plugins
plugins:
- jekyll-paginate

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink: /:title/


# Setup
title:            Logical Bee
description:      'programming blog'
url:              https://logicalbee.in
baseurl:
paginate:         20
paginate_path: "/archive/page:num"

# Custom vars
google_analytics: 

# see http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
  startings: [html, head, body]
  profile: false
  blanklines: false
  ignore:
    envs: [local]
