baseURL = "https://logicalbee.github.io/"
languageCode = "en-us"
title = "Sushanth Kurdekar"
rssLimit = 20
copyright = "2022 logicalbee All rights reserved"
minify = true

[Author]
  name = "Sushanth Kurdekar"
  email = "sushanth@logicalbee.in"

[permalinks]
  posts = "/:title"
  pages = "/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["html", "json", "rss"]

[params]
     Description = "The personal website, blog and dev diary of clairecodes"
     Adsclient = "ca-pub-6155459918319745"
     AdsinArticleSlot = "1336835070"