baseURL = 'https://logicalbee.in/'
languageCode = 'en-us'
title = 'Sushanth Kurdekar (Logical Bee)'
theme = 'hugo-bearblog'
minify = true


[[menu.main]]
  name = "home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "blog"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "resume"
  url = "/resume.pdf"
  weight = 3

[params]
  description = "My Internet home"
  author = "Sushanth Kurdekar"
  hideMadeWithLine = true
  favicon = "favicon.svg"

[services]
  [services.googleAnalytics]
    id = "G-WJT0MDZBL1"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

