baseURL = 'https://logicalbee.github.io/'
languageCode = 'en-us'
title = 'Sushanth Kurdekar'
theme = 'hugo-bearblog'
minify = true


[[menu.main]]
  name = "home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "blog"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "projects"
  url = "/projects/"
  weight = 4

[[menu.main]]
  name = "resume"
  url = "/resume.pdf"
  weight = 5

[params]
  description = "My Internet home"
  author = "Sushanth Kurdekar"
  hideMadeWithLine = true
  favicon = "favicon.svg"

[services]
  [services.googleAnalytics]
    id = "G-XXXXXXXX"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

